# Generated by Django 5.0.6 on 2024-06-22 17:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
